selenide-fix

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,212 +1,260 @@
-#
-# Copyright (c) 2022, Oracle and/or its affiliates. All rights reserved.
-# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
-#
-# This code is free software; you can redistribute it and/or modify it
-# under the terms of the GNU General Public License version 2 only, as
-# published by the Free Software Foundation.  Oracle designates this
-# particular file as subject to the "Classpath" exception as provided
-# by Oracle in the LICENSE file that accompanied this code.
-#
-# This code is distributed in the hope that it will be useful, but WITHOUT
-# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
-# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
-# version 2 for more details (a copy is included in the LICENSE file that
-# accompanied this code).
-#
-# You should have received a copy of the GNU General Public License version
-# 2 along with this work; if not, write to the Free Software Foundation,
-# Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
-#
-# Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
-# or visit www.oracle.com if you need additional information or have any
-# questions.
-#
-
 name: 'Run tests'
-
 on:
   push:
-    branches: [ loom ]
-
-
-
-
-
-
-
-
-
-
-
-
+    branches: [ selenide ]
 
 
 
 
 
 jobs:
-  test:
-    name: test
-    runs-on: ${{ inputs.runs-on }}
-    defaults:
-      run:
-        shell: bash
-
+  run-tests-on-windows:
+    runs-on: windows-latest
     strategy:
       fail-fast: false
       matrix:
-        test-name:
-          - 'jdk/tier1 part 1'
-          - 'jdk/tier1 part 2'
-          - 'jdk/tier1 part 3'
-          - 'langtools/tier1'
-          - 'hs/tier1 common'
-          - 'hs/tier1 compiler'
-          - 'hs/tier1 gc'
-          - 'hs/tier1 runtime'
-          - 'hs/tier1 serviceability'
-          - 'lib-test/tier1'
-
-        include:
-          - test-name: 'jdk/tier1 part 1'
-            test-suite: 'test/jdk/:tier1_part1'
-
-          - test-name: 'jdk/tier1 part 2'
-            test-suite: 'test/jdk/:tier1_part2'
-
-          - test-name: 'jdk/tier1 part 3'
-            test-suite: 'test/jdk/:tier1_part3'
-
-          - test-name: 'langtools/tier1'
-            test-suite: 'test/langtools/:tier1'
-
-          - test-name: 'hs/tier1 common'
-            test-suite: 'test/hotspot/jtreg/:tier1_common'
-            debug-suffix: -debug
-
-          - test-name: 'hs/tier1 compiler'
-            test-suite: 'test/hotspot/jtreg/:tier1_compiler'
-            debug-suffix: -debug
-
-          - test-name: 'hs/tier1 gc'
-            test-suite: 'test/hotspot/jtreg/:tier1_gc'
-            debug-suffix: -debug
-
-          - test-name: 'hs/tier1 runtime'
-            test-suite: 'test/hotspot/jtreg/:tier1_runtime'
-            debug-suffix: -debug
-
-          - test-name: 'hs/tier1 serviceability'
-            test-suite: 'test/hotspot/jtreg/:tier1_serviceability'
-            debug-suffix: -debug
-
-          - test-name: 'lib-test/tier1'
-            test-suite: 'test/lib-test/:tier1'
-            debug-suffix: -debug
-
+        gradle-task: [ 'check', 'edge_headless_smoke' ]
     steps:
-      - name: 'Checkout the JDK source'
-        uses: actions/checkout@v3
-
-      - name: 'Get MSYS2'
-        uses: ./.github/actions/get-msys2
-        if: runner.os == 'Windows'
-
-      - name: 'Get the BootJDK'
-        id: bootjdk
-        uses: ./.github/actions/get-bootjdk
+      - name: Checkout
+        uses: actions/checkout@v4
+      - name: Set up JDK
+        uses: actions/setup-java@v3
         with:
-          platform: ${{ inputs.bootjdk-platform }}
-
-      - name: 'Get JTReg'
-        id: jtreg
-        uses: ./.github/actions/get-jtreg
-
-      - name: 'Get bundles'
-        id: bundles
-        uses: ./.github/actions/get-bundles
+          distribution: 'temurin'
+          cache: 'gradle'
+          java-version: '17'
+      - name: Setup Edge
+        if: ${{ contains(matrix.gradle-task, 'edge') }}
+        uses: browser-actions/setup-edge@latest
+      - name: Set-DisplayResolution
+        shell: pwsh
+        run: Set-DisplayResolution -Width 1920 -Height 1080 -Force
+      - name: Build with Gradle
+        uses: gradle/gradle-build-action@v2
         with:
-          platform: ${{ inputs.platform }}
-          debug-suffix: ${{ matrix.debug-suffix }}
-
-      - name: 'Install dependencies'
-        run: |
-          # On macOS we need to install some dependencies for testing
-          brew install make
-          sudo xcode-select --switch /Applications/Xcode_11.7.app/Contents/Developer
-          # This will make GNU make available as 'make' and not only as 'gmake'
-          echo '/usr/local/opt/make/libexec/gnubin' >> $GITHUB_PATH
-        if: runner.os == 'macOS'
-
-      - name: 'Set PATH'
-        id: path
-        run: |
-          # We need a minimal PATH on Windows
-          # Set PATH to "", so just GITHUB_PATH is included
-          if [[ '${{ runner.os }}' == 'Windows' ]]; then
-            echo "value=" >> $GITHUB_OUTPUT
-          else
-            echo "value=$PATH" >> $GITHUB_OUTPUT
-          fi
-
-      - name: 'Run tests'
-        id: run-tests
-        run: >
-          make test-prebuilt
-          TEST='${{ matrix.test-suite }}'
-          BOOT_JDK=${{ steps.bootjdk.outputs.path }}
-          JT_HOME=${{ steps.jtreg.outputs.path }}
-          JDK_IMAGE_DIR=${{ steps.bundles.outputs.jdk-path }}
-          SYMBOLS_IMAGE_DIR=${{ steps.bundles.outputs.symbols-path }}
-          TEST_IMAGE_DIR=${{ steps.bundles.outputs.tests-path }}
-          JTREG='JAVA_OPTIONS=-XX:-CreateCoredumpOnCrash;VERBOSE=fail,error,time;KEYWORDS=!headful'
-          && bash ./.github/scripts/gen-test-summary.sh "$GITHUB_STEP_SUMMARY" "$GITHUB_OUTPUT"
-        env:
-          PATH: ${{ steps.path.outputs.value }}
-
-        # This is a separate step, since if the markdown from a step gets bigger than
-        # 1024 kB it is skipped, but then the short summary above is still generated
-      - name: 'Generate test report'
-        run: bash ./.github/scripts/gen-test-results.sh "$GITHUB_STEP_SUMMARY"
+          arguments: ${{ matrix.gradle-task }} --no-parallel --no-daemon --console=plain
+      - uses: actions/upload-artifact@v3
         if: always()
+        with:
+          name: test-report-win-${{matrix.gradle-task}}
+          retention-days: 14
+          path: |
+            **/build/reports
+            **/build/test-results
 
-      - name: 'Package test results'
-        id: package
+  run-tests-on-linux:
+    runs-on: ubuntu-latest
+    strategy:
+      fail-fast: false
+      matrix:
+        gradle-task: [ 'check', 'firefox_headless', 'chrome_headless' ]
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+      - name: Set up JDK
+        uses: actions/setup-java@v3
+        with:
+          distribution: 'temurin'
+          cache: 'gradle'
+          java-version: '17'
+      - name: Setup Firefox
+        if: ${{ matrix.gradle-task != 'check' }}
+        uses: browser-actions/setup-firefox@latest
+      - name: Build with Gradle
+        uses: gradle/gradle-build-action@v2
+        with:
+          arguments: ${{ matrix.gradle-task }} --no-parallel --no-daemon --console=plain
+      - uses: actions/upload-artifact@v3
+        if: always()
+        with:
+          name: test-report-linux-${{matrix.gradle-task}}
+          retention-days: 14
+          path: |
+            **/build/reports
+            **/build/test-results
+
+
+  run-android-tests:
+    runs-on: macOS-12
+    env:
+      APPIUM_TEST_SERVER_PORT: 4723
+      APPIUM_TEST_SERVER_HOST: 127.0.0.1
+      APPIUM_STARTUP_TIMEOUT_SEC: 30
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+      - name: Set up JDK
+        uses: actions/setup-java@v3
+        with:
+          distribution: 'temurin'
+          cache: 'gradle'
+          java-version: '11'
+      - uses: actions/cache@v3
+        with:
+          path: build/apps
+          key: ${{ runner.os }}-android-tests-${{ hashFiles('**/*.zip*') }}
+          restore-keys: |
+            ${{ runner.os }}-android-tests-
+      - name: Setup NodeJS
+        uses: actions/setup-node@v3
+        with:
+          node-version: '18'
+      - name: Install Appium
         run: |
-          # Package test-results and relevant parts of test-support
-          mkdir results
-
-          if [[ -d build/run-test-prebuilt/test-results ]]; then
-            cd build/run-test-prebuilt/test-results/
-            zip -r -9 "$GITHUB_WORKSPACE/results/test-results.zip" .
-            cd $GITHUB_WORKSPACE
-          else
-            echo '::warning ::Missing test-results directory'
-          fi
-
-          if [[ -d build/run-test-prebuilt/test-support ]]; then
-            cd build/run-test-prebuilt/test-support/
-            zip -r -9 "$GITHUB_WORKSPACE/results/test-support.zip" . -i *.jtr -i */hs_err*.log -i */replay*.log
-            cd $GITHUB_WORKSPACE
-          else
-            echo '::warning ::Missing test-support directory'
-          fi
-
-          artifact_name="results-${{ inputs.platform }}-$(echo ${{ matrix.test-name }} | tr '/ ' '__')"
-          echo "artifact-name=$artifact_name" >> $GITHUB_OUTPUT
-        if: always()
-
-      - name: 'Upload test results'
-        uses: actions/upload-artifact@v3
+          npm install -g appium@next
+          npm install -g appium-doctor
+      - name: Start Appium server
+        run: |
+          cwd=$(pwd)
+          pushd "$cwd"
+          cd ~
+          appium driver install uiautomator2
+          appium-doctor
+          nohup appium \
+            --base-path /wd/hub \
+            --relaxed-security \
+            2>&1 > "$cwd/appium.log" &
+          popd
+      - name: Wait for Appium server startup
+        run: |
+          seconds_started=$(date +%s)
+          while ! nc -z $APPIUM_TEST_SERVER_HOST $APPIUM_TEST_SERVER_PORT; do
+            sleep 0.1
+            seconds_elapsed=$(( $(date +%s) - seconds_started ))
+            if [[ $seconds_elapsed -gt $APPIUM_STARTUP_TIMEOUT_SEC ]]; then
+              echo "Appium server was unable to start within $APPIUM_STARTUP_TIMEOUT_SEC seconds timeout"
+              exit 1
+            fi
+          done
+      - name: Run tests
+        uses: reactivecircus/android-emulator-runner@v2
         with:
-          path: results
-          name: ${{ steps.package.outputs.artifact-name }}
+          api-level: 28
+          profile: pixel_3_xl
+          disable-animations: true
+          emulator-options: -no-snapshot -no-window -no-boot-anim -camera-back emulated -camera-front emulated -gpu swiftshader_indirect
+          script: ./gradlew clean android --info
+      - uses: actions/upload-artifact@v3
         if: always()
-
-        # This is the best way I found to abort the job with an error message
-      - name: 'Notify about test failures'
-        uses: actions/github-script@v6
         with:
-          script: core.setFailed('${{ steps.run-tests.outputs.error-message }}')
-        if: steps.run-tests.outputs.failure == 'true'
+          name: test-report-android
+          path: |
+            **/build/reports
+            **/build/test-results
+            **/appium.log
+
+  run-ios-tests:
+    runs-on: macOS-12
+    env:
+      APPIUM_TEST_SERVER_PORT: 4723
+      APPIUM_TEST_SERVER_HOST: 127.0.0.1
+      APPIUM_STARTUP_TIMEOUT_SEC: 30
+    steps:
+      - uses: actions/checkout@v4
+      - name: Setup iOS simulator
+        uses: futureware-tech/simulator-action@v2
+        with:
+          model: 'iPhone 14'
+          os: 'iOS'
+          os_version: '16.2'
+      - uses: actions/cache@v3
+        with:
+          path: build/apps
+          key: ${{ runner.os }}-ios-tests-${{ hashFiles('**/*.zip*') }}
+          restore-keys: |
+            ${{ runner.os }}-ios-tests-
+      - name: Setup NodeJS
+        uses: actions/setup-node@v3
+        with:
+          node-version: '18'
+      - name: Install Appium
+        run: |
+          npm install -g appium@next
+          npm install -g appium-doctor
+      - name: Log Xcode Version
+        run: xcodebuild -version
+      - name: Log Installed Simulators
+        run: xcrun simctl list
+      - name: Log Runtimes
+        run: xcrun simctl list runtimes
+      - name: Start Appium server
+        run: |
+          cwd=$(pwd)
+          pushd "$cwd"
+          cd ~
+          appium driver install xcuitest
+          appium driver install safari
+          appium-doctor
+          nohup appium \
+            --base-path /wd/hub \
+            --relaxed-security \
+            2>&1 > "$cwd/appium.log" &
+          popd
+      - name: Wait for Appium server startup
+        run: |
+          seconds_started=$(date +%s)
+          while ! nc -z $APPIUM_TEST_SERVER_HOST $APPIUM_TEST_SERVER_PORT; do
+            sleep 0.1
+            seconds_elapsed=$(( $(date +%s) - seconds_started ))
+            if [[ $seconds_elapsed -gt $APPIUM_STARTUP_TIMEOUT_SEC ]]; then
+              echo "Appium server was unable to start within $APPIUM_STARTUP_TIMEOUT_SEC seconds timeout"
+              exit 1
+            fi
+          done
+      - name: Set up JDK
+        uses: actions/setup-java@v3
+        with:
+          distribution: 'temurin'
+          cache: 'gradle'
+          java-version: '11'
+      - name: Run iOS tests
+        run: ./gradlew ios --no-daemon --console=plain -i
+      - uses: actions/upload-artifact@v3
+        if: always()
+        with:
+          name: test-report-ios
+          path: |
+            **/build/reports
+            **/build/test-results
+            **/appium.log
+
+  run-selenoid-tests:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+      - uses: actions/setup-java@v3
+        with:
+          distribution: 'temurin'
+          cache: 'gradle'
+          java-version: '11'
+      - name: Start selenoid
+        uses: Xotabu4/selenoid-github-action@v2
+      - name: Run integration tests
+        uses: gradle/gradle-build-action@v2
+        with:
+          arguments: selenoidTests
+      - uses: actions/upload-artifact@v3
+        if: always()
+        with:
+          name: test-report-selenoid
+          path: |
+            **/build/reports
+            **/build/test-results
+
+  auto-merge-dependabot:
+    name: 🤖 Auto merge dependabot PR
+    timeout-minutes: 10
+    needs: [run-tests-on-linux, run-tests-on-windows, run-android-tests, run-ios-tests, run-selenoid-tests]
+    if: ${{ github.actor == 'dependabot[bot]' }}
+    runs-on: ubuntu-latest
+    permissions:
+      pull-requests: write
+      contents: write
+    steps:
+      - name: 🤖 Merge PR from dependabot
+        uses: fastify/github-action-merge-dependabot@v3.9.1
+        with:
+          github-token: ${{secrets.GITHUB_TOKEN}}
+          target: minor
+          merge-method: rebase
